### ISSUE TITLE
Some elements don't inherit their font family, set their font familiy explicitly

### ISSUE THREAD

**Issue by alshakero** [alshakerM/my-imitategram#12]
Currently, we have `font-family` in `body`. But this doesn't apply to 

`button`, `input`, and `textarea`. We need to add font family to these in App.css.

```css
body, button, input, textarea {
    font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
}
```
